export const LanguageNameType = {
    AA: 'Afar',
    AB: 'Аҧсуа',
    AF: 'Afrikaans',
    AK: 'Akan',
    AM: 'አማርኛ',
    AN: 'Aragonés',
    AR: 'العربية',
    AS: 'অসমীয়া',
    AV: 'Авар мацӀ',
    AY: 'Aymar aru',
    AZ: 'Azərbaycan dili',
    BA: 'Башҡорт теле',
    BE: 'Беларуская',
    BG: 'Български',
    BI: 'Bislama',
    BM: 'Bamanankan',
    BN: 'বাংলা',
    BO: 'བོད་ཡིག',
    BR: 'Brezhoneg',
    BS: 'Bosanski',
    CA: 'Català',
    CE: 'Нохчийн мотт',
    CEB: 'Cebuano',
    CH: 'Chamoru',
    CHM: 'Марий йылме',
    CKB: 'کوردیی ناوەندی',
    CO: 'Corsu',
    CS: 'Čeština',
    CV: 'Чӑвашла',
    CY: 'Cymraeg',
    DA: 'Dansk',
    DE: 'Deutsch',
    DV: 'ދިވެހި',
    DZ: 'རྫོང་ཁ',
    EE: 'Eʋegbe',
    EL: 'Ελληνικά',
    EN_AU: 'English (Australia)',
    EN_CA: 'English (Canada)',
    EN_GH: 'English (Ghana)',
    EN_HK: 'English (Hong Kong)',
    EN_IE: 'English (Ireland)',
    EN_IN: 'English (India)',
    EN_KE: 'English (Kenya)',
    EN_NG: 'English (Nigeria)',
    EN_NZ: 'English (New Zealand)',
    EN_PH: 'English (Philippines)',
    EN_SG: 'English (Singapore)',
    EN_TZ: 'English (Tanzania)',
    EN_US: 'English (United States)',
    EN_ZA: 'English (South Africa)',
    EN: 'English',
    EO: 'Esperanto',
    ES_MX: 'Español (México)',
    ES: 'Español',
    ET: 'Eesti',
    EU: 'Euskara',
    FA: 'فارسی',
    FI: 'Suomi',
    FJ: 'Vosa Vakaviti',
    FO: 'Føroyskt',
    FR: 'Français',
    FY: 'Frysk',
    GA: 'Gaeilge',
    GD: 'Gàidhlig',
    GL: 'Galego',
    GN: "Avañe'ẽ",
    GU: 'ગુજરાતી',
    GV: 'Gaelg',
    HA: 'Hausa',
    HAW: 'ʻŌlelo Hawaiʻi',
    HE: 'עברית',
    HI: 'हिन्दी',
    HMN: 'Hmoob',
    HO: 'Hiri Motu',
    HR: 'Hrvatski',
    HT: 'Kreyòl ayisyen',
    HU: 'Magyar',
    HY: 'Հայերեն',
    IA: 'Interlingua',
    ID: 'Bahasa Indonesia',
    IE: 'Interlingue',
    IG: 'Igbo',
    ILO: 'Ilokano',
    INTERSLAVIC: 'Medžuslovjanski',
    IO: 'Ido',
    IS: 'Íslenska',
    IT: 'Italiano',
    JA: '日本語',
    JV: 'ꦧꦱꦗꦮ',
    KA: 'ქართული',
    KG: 'Kikongo',
    KI: 'Gĩkũyũ',
    KK: 'Қазақ тілі',
    KL: 'Kalaallisut',
    KM: 'ខ្មែរ',
    KN: 'ಕನ್ನಡ',
    KO: '한국어',
    KR: 'Kanuri',
    KRI: 'Krio',
    KS: 'कश्मीरी / كشميري',
    KU: 'Kurdî / كوردی',
    KV: 'Коми кыв',
    KW: 'Kernewek',
    KY: 'Кыргызча',
    LA: 'Latina',
    LB: 'Lëtzebuergesch',
    LG: 'Luganda',
    LN: 'Lingála',
    LO: 'ລາວ',
    LT: 'Lietuvių',
    LU: 'Tshiluba',
    LUS: 'Mizo ṭawng',
    LV: 'Latviešu',
    MG: 'Malagasy',
    MH: 'Kajin M̧ajeļ',
    MI: 'Te Reo Māori',
    MK: 'Македонски',
    ML: 'മലയാളം',
    MN: 'Монгол',
    MNI: 'মণিপুরী',
    MR: 'मराठी',
    MRJ: 'Кырык мары',
    MS: 'Bahasa Melayu',
    MT: 'Malti',
    MY: 'မြန်မာစာ',
    NA: 'Ekakairũ Naoero',
    NB: 'Norsk Bokmål',
    ND: 'isiNdebele',
    NE: 'नेपाली',
    NL: 'Nederlands',
    NN: 'Norsk Nynorsk',
    NO: 'Norsk',
    NON: 'Norrǿnt mál',
    NR: 'isiNdebele',
    NY: 'Chinyanja',
    OC: 'Occitan',
    OM: 'Afaan Oromoo',
    OR: 'ଓଡ଼ିଆ',
    OS: 'Ирон æвзаг',
    OTO: 'Otomí',
    PA: 'ਪੰਜਾਬੀ / پنجابی',
    PAP: 'Papiamentu',
    PL: 'Polski',
    PS: 'پښتو',
    PT_BR: 'Português (Brasil)',
    PT: 'Português',
    QU: 'Runa Simi',
    RM: 'Rumantsch',
    RN: 'Ikirundi',
    RO: 'Română',
    RU: 'Русский',
    RW: 'Kinyarwanda',
    SC: 'Sardu',
    SD: 'سنڌي',
    SE: 'Sámegiella',
    SG: 'Sängö',
    SI: 'සිංහල',
    SK: 'Slovenčina',
    SL: 'Slovenščina',
    SM: 'Gagana Samoa',
    SN: 'ChiShona',
    SO: 'Soomaaliga',
    SQ: 'Shqip',
    SR: 'Српски',
    SS: 'SiSwati',
    ST: 'Sesotho',
    SU: 'Basa Sunda',
    SV: 'Svenska',
    SW: 'Kiswahili',
    TA: 'தமிழ்',
    TE: 'తెలుగు',
    TG: 'Тоҷикӣ',
    TH: 'ไทย',
    TI: 'ትግርኛ',
    TK: 'Türkmençe',
    TL: 'Wikang Tagalog',
    TN: 'Setswana',
    TO: 'Lea Faka-Tonga',
    TR: 'Türkçe',
    TT: 'Татарча',
    TY: 'Reo Tahiti',
    UDM: 'Удмурт кыл',
    UG: 'ئۇيغۇرچە',
    UK: 'Українська',
    UR: 'اردو',
    UZ: 'Oʻzbekcha',
    VI: 'Tiếng Việt',
    VO: 'Volapük',
    XH: 'isiXhosa',
    XX: 'Unknown',
    YI: 'ייִדיש',
    YO: 'Yorùbá',
    YUA: 'Yukatek Maya',
    ZH: '中文',
    ZU: 'isiZulu',
} as const

export type LanguageNameType = (typeof LanguageNameType)[keyof typeof LanguageNameType]
