/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CallbackImport } from './routes/callback'
import { Route as PublicRouteImport } from './routes/_public/route'
import { Route as ProtectedRouteImport } from './routes/_protected/route'
import { Route as DeveloperIndexImport } from './routes/developer/index'
import { Route as ProtectedIndexImport } from './routes/_protected/index'
import { Route as PublicLoginImport } from './routes/_public/login'
import { Route as DeveloperErrorsIndexImport } from './routes/developer/errors/index'
import { Route as DeveloperErrorsMonitorImport } from './routes/developer/errors/monitor'

// Create/Update Routes

const CallbackRoute = CallbackImport.update({
  path: '/callback',
  getParentRoute: () => rootRoute,
} as any)

const PublicRouteRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedRouteRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const DeveloperIndexRoute = DeveloperIndexImport.update({
  path: '/developer/',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedIndexRoute = ProtectedIndexImport.update({
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const PublicLoginRoute = PublicLoginImport.update({
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any)

const DeveloperErrorsIndexRoute = DeveloperErrorsIndexImport.update({
  path: '/developer/errors/',
  getParentRoute: () => rootRoute,
} as any)

const DeveloperErrorsMonitorRoute = DeveloperErrorsMonitorImport.update({
  path: '/developer/errors/monitor',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRoute
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRoute
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackImport
      parentRoute: typeof rootRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginImport
      parentRoute: typeof PublicRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/developer/': {
      id: '/developer/'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperIndexImport
      parentRoute: typeof rootRoute
    }
    '/developer/errors/monitor': {
      id: '/developer/errors/monitor'
      path: '/developer/errors/monitor'
      fullPath: '/developer/errors/monitor'
      preLoaderRoute: typeof DeveloperErrorsMonitorImport
      parentRoute: typeof rootRoute
    }
    '/developer/errors/': {
      id: '/developer/errors/'
      path: '/developer/errors'
      fullPath: '/developer/errors'
      preLoaderRoute: typeof DeveloperErrorsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  ProtectedRouteRoute: ProtectedRouteRoute.addChildren({ ProtectedIndexRoute }),
  PublicRouteRoute: PublicRouteRoute.addChildren({ PublicLoginRoute }),
  CallbackRoute,
  DeveloperIndexRoute,
  DeveloperErrorsMonitorRoute,
  DeveloperErrorsIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_protected",
        "/_public",
        "/callback",
        "/developer/",
        "/developer/errors/monitor",
        "/developer/errors/"
      ]
    },
    "/_protected": {
      "filePath": "_protected/route.tsx",
      "children": [
        "/_protected/"
      ]
    },
    "/_public": {
      "filePath": "_public/route.tsx",
      "children": [
        "/_public/login"
      ]
    },
    "/callback": {
      "filePath": "callback.tsx"
    },
    "/_public/login": {
      "filePath": "_public/login.tsx",
      "parent": "/_public"
    },
    "/_protected/": {
      "filePath": "_protected/index.tsx",
      "parent": "/_protected"
    },
    "/developer/": {
      "filePath": "developer/index.tsx"
    },
    "/developer/errors/monitor": {
      "filePath": "developer/errors/monitor.tsx"
    },
    "/developer/errors/": {
      "filePath": "developer/errors/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
